// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cmasum
double cmasum(NumericMatrix te);
RcppExport SEXP mbgraphic_cmasum(SEXP teSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type te(teSEXP);
    rcpp_result_gen = Rcpp::wrap(cmasum(te));
    return rcpp_result_gen;
END_RCPP
}
// variableflip
NumericMatrix variableflip(NumericMatrix te, int i, int j);
RcppExport SEXP mbgraphic_variableflip(SEXP teSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type te(teSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(variableflip(te, i, j));
    return rcpp_result_gen;
END_RCPP
}
