# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmasum <- function(te) {
    .Call('mbgraphic_cmasum', PACKAGE = 'mbgraphic', te)
}

variableflip <- function(te, i, j) {
    .Call('mbgraphic_variableflip', PACKAGE = 'mbgraphic', te, i, j)
}

